/// Flutter icons StarWarsIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StarWarsIcons
///      fonts:
///       - asset: fonts/StarWarsIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

// Clase con íconos personalizados creados por mi.
class StarWarsIcons {
  StarWarsIcons._();

  static const _kFontFam = 'StarWarsIcons';
  static const String? _kFontPkg = null;

  static const IconData darthVader =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoda =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
